<?xml version="1.0"?>
<package format="3">
  <name>painting_cell</name><version>0.1.0</version>
  <description>UR20 car painting demonstration</description>
  <maintainer email="aditya@example.com">Aditya Pachauri</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend><exec_depend>ur_description</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend><exec_depend>xacro</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend><exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>gz_ros2_control</exec_depend><exec_depend>joint_trajectory_controller</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend><exec_depend>controller_manager</exec_depend>
  <exec_depend>moveit_ros_move_group</exec_depend><exec_depend>moveit_kinematics</exec_depend>
  <exec_depend>moveit_planners_ompl</exec_depend><exec_depend>moveit_msgs</exec_depend>
  <exec_depend>control_msgs</exec_depend><exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend><exec_depend>shape_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend><exec_depend>rviz2</exec_depend>
  <exec_depend>python3-numpy</exec_depend><exec_depend>python3-scipy</exec_depend>
  <exec_depend>python3-yaml</exec_depend><exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch_ros</exec_depend><exec_depend>tf2_ros_py</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
